# numpy
<pr>Numpy is the core library for sceintific computing in Python. It provides a high-performance multidimentional array object and tools for working with these arrays. 
    </pr>

In [62]:
import numpy as np

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

In [65]:
# Creating a numpy array object
array = np.array([1,4,5,6,7], int)

In [66]:
print(array)
array.dtype

[1 4 5 6 7]


dtype('int64')

In [68]:
# creating a two dimentional array object
array_2d = np.array([[64,84,21,3,8,1], [4,3,89,1,40,5]], int)
print(array_2d)

[[64 84 21  3  8  1]
 [ 4  3 89  1 40  5]]


In [70]:
array_2d.shape

(2, 6)

In [71]:
# giving new shape to the array
np.reshape(array_2d, (6, 2))

array([[64, 84],
       [21,  3],
       [ 8,  1],
       [ 4,  3],
       [89,  1],
       [40,  5]])

In [72]:
# array indexing

print(array_2d[0], array_2d[1][1:])
print(array_2d[0, :], array_2d[1, 1:])

[64 84 21  3  8  1] [ 3 89  1 40  5]
[64 84 21  3  8  1] [ 3 89  1 40  5]


In [73]:
a = np.array([2, 4, 67, 7], int)
b = np.array([75, 814, 9, 1], int)

print('Addition of two arrays -')
print(np.add(a, b))

print('Subtraction of two arrays -')
print(np.subtract(a, b))

print('Element-wise multiplication of two arrays -')
print(np.multiply(a, b))

print('Element-wise division of two arrays -')
print(np.divide(a, b))

print('Taking square root of each element in the array -')
print(np.sqrt(a))

Addition of two arrays -
[ 77 818  76   8]
Subtraction of two arrays -
[ -73 -810   58    6]
Element-wise multiplication of two arrays -
[ 150 3256  603    7]
Element-wise division of two arrays -
[2.66666667e-02 4.91400491e-03 7.44444444e+00 7.00000000e+00]
Taking square root of each element in the array -
[1.41421356 2.         8.18535277 2.64575131]


In [74]:
# finding the mean of array a
print(np.mean(a))

# finding the meadian of array b
print(np.median(b))

# dot product of array a and b
print(np.dot(a, b))

20.0
42.0
4016


printing array objects with dimention 2 X 2 having all -
<ul>
    <li>zero entries</li>
    <li>ones</li>
    <li>number 45</li>
    <li>random numbers</li>
</ul>

In [76]:
print(np.zeros((2, 2)))
print(np.ones((2,2)))
print(np.full((2,2), 45))
print(np.random.random((2, 2)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[45 45]
 [45 45]]
[[0.54371998 0.70723687]
 [0.26132608 0.09113901]]
